### ISSUE TITLE
NanoELS - try first

### ISSUE THREAD

**Issue by jvojvodi** [kachurovskiy/nanoels#139]
I need help
Everything is connected. (see pictures) The encoder makes a full circle on the display and shows an angle of 360°. Correct. 
The problem is that the stepper does not start.
No matter what I do, the stepper stops.
Where am I wrong.

[Greeting

![IMG_0968](https://github.com/kachurovskiy/nanoels/assets/150443240/e61149ab-8349-40e2-b89e-9af8c08ce9dd)
![IMG_0969](https://github.com/kachurovskiy/nanoels/assets/150443240/5b39dddb-4ea8-471d-82ec-3484de2906f0)
![IMG_0970](https://github.com/kachurovskiy/nanoels/assets/150443240/593df145-3a4b-49e1-84a1-968f2ffc9ad0)
![IMG_0971](https://github.com/kachurovskiy/nanoels/assets/150443240/60d38576-90ad-4544-ae51-1dcc1b52429b)

**Comment by jvojvodi** [comment]
The video is not ideal, the display is not visible in wide view. But maybe this one will help.
The third and fourth lines of the display disappear when the encoder is turned. Is that normal?
Also, the stepper heats up a lot in this experiment.

https://github.com/kachurovskiy/nanoels/assets/150443240/8ba8e45f-0c49-4ddd-8657-60c17f61a30d

**Comment by kachurovskiy** [comment]
Bottom lines disappearing during motion is intended since Nano only has 1 core and can either drive the motor or update the screen.

Look for the 24/5v switch on the side of your driver, ensure it's in the 5v position.

**Comment by jvojvodi** [comment]
5V works wonders:) Everything works fine on the test bench. Now comes the implementation on my DIY lathe.
Thanks again
Greeting
