### ISSUE TITLE
Fitting to WM180

### ISSUE THREAD

**Issue by Colinsp** [kachurovskiy/nanoels#166]
I am planning on fitting this to the WM180 lathe. The cross slide is identical so there is no issue there. However, the lathe spindle has a gear with only 40 teeth for the encoder. As a result neither this or the alternative gear wheels are suitable. Do you have suggestions for a suitable alternative please?

**Comment by kachurovskiy** [comment]
Hi @Colinsp, can you please post some pictures of the relevant pieces of your lathe? Dimensions would also be helpful 👍

**Comment by Colinsp** [comment]
The photo shows the headstock end of my lathe with the change gears removed so you can see more. I hope this helps.

**Comment by kachurovskiy** [comment]
Got it. Can you give me A and B dimensions?

![image](https://github.com/kachurovskiy/nanoels/assets/517919/ddda075a-05e1-498a-96c3-8d49e58d6aae)

**Comment by Colinsp** [comment]
I am not sure what you mean  by A from your drawing. If it is the diameter of the 40 tooth gear it is 42mm.

B is 23mm.
Thanks Colin

**Comment by kachurovskiy** [comment]
Just recalled that this was already solved before in https://github.com/kachurovskiy/nanoels/discussions/159 - let's follow-up there.
