### ISSUE TITLE
Gcode tool with not accounted for 

### ISSUE THREAD

**Issue by KyrreKnive** [kachurovskiy/nanoels#169]
STOCK D6
TOOL ROUND R0.1 L1.5

L3 DS0 DE6 CONV

L3 DS6 DE0 CONV
L2 D3
L3 DS3 DE6

![image](https://github.com/kachurovskiy/nanoels/assets/142929705/c8adc862-977c-4329-bf09-a97eb5ba1a1a)

**Comment by kachurovskiy** [comment]
You've specified round tool with a very small radius, did you mean to use a RECT tool?

**Comment by KyrreKnive** [comment]
Yes, I am ssorry thats my fault.

**Comment by kachurovskiy** [comment]
No worries, I need to make it show an error when L is specified for a round tool and when tool is smaller than the pass width. Also showing the tool in UI would help.

**Comment by KyrreKnive** [comment]
I am using excel to tweek the final gcode. Changes in the editor is not vizible in grafic display?
![image](https://github.com/kachurovskiy/nanoels/assets/142929705/6ceb4470-37ca-4a12-b500-36a134d9c17d)

**Comment by kachurovskiy** [comment]
Wow, that's very smart 🤓 You can preview any gcode on sites like ncviewer.com

**Comment by KyrreKnive** [comment]
Yes I just paste the code in column A and calculate absolute coordinates in columns E(Z) and F(X)

**Comment by Festivejelly** [comment]
@KyrreKnive this tool might help you https://festivejelly.github.io/LatheGcodeVisualiser/ I made it to help me tweak my gcode. Supports absolute and relative co ordinates.
