### ISSUE TITLE
Modified mount for slightly different encoder

### ISSUE THREAD

**Issue by mockendon** [kachurovskiy/nanoels#18]
The encoder I bought is a little different from the one you show.  The somewhat bulky cable exit gland prompted a modification.  I also added some tabs for machine screws in tapped holes in the headstock casting - one is oval to allow adjustment of backlash between the gears.

[https://www.thingiverse.com/thing:5156081](url)

**Comment by mockendon** [comment]
Also I modified the stepper mount to add a pinch bolt.

[https://www.thingiverse.com/thing:5156087](url)

**Comment by kachurovskiy** [comment]
Matt, awesome, thank you! Linked your models in https://github.com/kachurovskiy/nanoels/commit/70b1cbc75f77e74161bcae6a57df76f97c80c6c7
