### ISSUE TITLE
Hello, Someone could explain how the program works? Thanks

### ISSUE THREAD

**Issue by lewiss66** [kachurovskiy/nanoels#2]

**Comment by kachurovskiy** [comment]
It works by first calling setup() function and then calling loop() infinitely.

setup() among other things adds an interrupt handler spinEnc() which is called every time a rotary encoder makes a step, adding those steps up in `spindlePos` variable.

loop() calculates the stepper position based on `spindlePos` and compares it to current stepper position. Stepper is moved if needed.

**Comment by lewiss66** [comment]
Thanks, It a good help to start understanding !
