### ISSUE TITLE
Word of caution for older mini-lathes

### ISSUE THREAD

**Issue by mockendon** [kachurovskiy/nanoels#26]
In your readme you allude to lathe main board (speed controller) failure associated with a short to the case from the control panel.  I was, therefore, very careful never to run the lathe when the panel was 'floating'.  However - once the project was finished and everything was working perfectly (amazing, by the way - another post with pics of the finished article will follow) I gave in to the obvious temptation to 'see what it could do'  ie. took the lathe speed up to the max.  That is what blew up my (rather old) control board.  The mode of failure was interesting (a pair of diodes across the supply failed short circuit) but it had nothing to do with NanoELS it is just that I had almost never run the lathe at top speed and the ageing control electronics wasn't up to it.  Still, it was an interesting fault finding mission and I learned something about SCRs as high voltage DC speed controllers along the way.

**Comment by kachurovskiy** [comment]
Matt, great data point, thanks for sharing, hopefully your warning will save a few control boards.
