### ISSUE TITLE
AIN device connected to A6 and A7 pins

### ISSUE THREAD

**Issue by oppozith** [kachurovskiy/nanoels#65]
Hi!
What is the device that marked as "AIN" on scheme connected to A6 and A7 pins?

Thanks.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/5749538/178088600-8bf3fb24-4bba-4396-9dce-495fe16eb625.png">

**Comment by kachurovskiy** [comment]
@oppozith A6 and A7 aren't used by NanoEls but are exposed in case you want to modify the code and use them for something. Sorry for confusion. Thanks!

**Comment by oppozith** [comment]
Understood.
Thank you for your projects!
